---
title: "Homework5"
author: "Anna Schmoker"
date: "2/14/2018"
output: 
  html_document: 
    highlight: tango
    theme: cerulean
---
1. The primary reason for using Excel to set up data frames is that people like to have the columns aligned. However, if there are not too many columns, it may be faster to do the job in a plain text editor first and align the columns with tabs. In your text editor, type in (or copy and paste from here) the following lines of text:

```
STRING:
First String    Second      1.22      3.4
Second          More Text   1.555555  2.2220
Third           x           3         124
```
SOLUTION:
Find any two or more consecutive spaces.
Replace with a comma, followed by a space.

```
FIND: \s{2,}
  
REPLACE: ,
  
OUTPUT:
First String, Second , 1.22, 3.4
Second, More Text, 1.555555, 2.2220
Third, x , 3, 124
```

2. A True Regex Story. I am preparing a collaborative NSF grant with a colleague at another university. One of the pieces of an NSF grant is a listing of potential conflicts of interest. NSF wants to know the first and last name of the collaborator and their institution.

```
STRING:
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr
```
SOLUTION:
Find a word, plus another word, plus the rest of the line. () selects items to include in the REPLACE action.
Replace with the second item, then the first item, then the third item in parentheses.
```
FIND: (\w+), (\w+), (.*)

REPLACE: \2 \1 (\3)

OUTPUT: 
Bryan Ballif (University of Vermont)
Aaron Ellison (Harvard Forest)
Sydne Record (Bryn Mawr)
```

3. A Second True Regex Story. A few weeks ago, at Radio Bean’s Sunday afternoon old-time music session, one of the mandolin players gave me a DVD with over 1000 historic recordings of old-time fiddle tunes.

The list of tunes (shown here as a single line of text) looks like this:

```
INPUT:
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3
```
Unfortunately, in this form, you can’t re-order the file names to put them in alphabetical order. I thought I could just strip out the leading numbers, but this will cause a conflict, because, for wildly popular tunes such as “Shove That Pig’s Foot A Little Further In The Fire”, there are multiple copies somewhere in the list.

All of these files are on a single line, so first write a regular expression to place each file name on its own line:

SOLUTION:
Find ".mp3" followed by a space
Replace with ".mp3" followed by a line breal

```
FIND: \.mp3\s

REPLACE: \.mp3\r

OUPUT:
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Cherokee Shuffle.mp3
0004 Walking Cane.mp3
```

Now write a regular expression to grab the four digit number and put it at the end of the title:

SOLUTION:
Find a number, followed by a space, followed by a word + the rest of the line until .mp3". Select the item in ()
Replace with item 2, underscore, item 1 item 3

```
FIND: (\d+)\s(\w+.*)(\.mp3).*

REPLACE: \2_\1\3

OUPUT:
Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Cherokee Shuffle_0003.mp3
Walking Cane_0004.mp3
```

4. Here is a data frame with genus, species, and two numeric variables.

```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55
```
Write a single regular expression to rearrange the data set like this:

SOLUTION:
Find a letter followed by the rest of the word comma another word comma everything else until another comma followed by a number
Replace with the first letter followed by an underscore followed by the second word followed by the last number.

```
FIND: (\w)\w+,(\w+),.*,(\d+)

REPLACE: \1_\2,\3

OUTPUT:
C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55
```

Beginning with the original expression, rearrange it to abbreviate the species name like this:

SOLUTION:
Replace the second word with only the first four letters of the second word (everything else stays)

```
FIND: (\w_)(\w{4}).*,(\d+)

REPLACE: \1\2,\3

OUTPUT:
C_penn,44
C_herc,3
M_punc,4
L_neon,55
```