---
title: "Homework10"
author: "Anna Schmoker"
date: "3/28/2018"
output: 
  html_document: 
    highlight: tango
    theme: cerulean
---
### Batch Processing

```{r,warning=FALSE}
####################################################
# Function: FileBuilder
# create a set of random files for regression
# input: fileN = number of files, fileFolder = name of folder for random files, fileSize = c(min,max) number of rows in file, fileNA = number on average of NA per column
# output: set of random files
#---------------------------------------------------
FileBuilder <- function(fileN=10,
                        fileFolder="RandomFilesHW10/",
                        fileSize=c(15,100),
                        fileNA=3) {
  for(i in seq_len(fileN)) {
    fileLength <- sample(fileSize[1]:fileSize[2],size=1)
    varX <- runif(fileLength) # random x values
    varY <- runif(fileLength) # random y values
    dF <- data.frame(varX,varY) # bind to data frame
    badVals <- rpois(n=1,lambda=fileNA) # number of NA
    dF[sample(nrow(dF),size=badVals),1] <- NA
    dF[sample(nrow(dF),size=badVals),2] <- NA
    # create a consecutive file name for this data frame
    fileLabel <- paste(fileFolder,
                       "ranFile",
                       formatC(i,
                               width=3,
                               format="d",
                               flag="0"),
                       ".csv",
                       sep="")
    # set up data file and incorporate time stamp and minimal metadata
    write.table(cat("# Simulated random data file for batch processing",
                    "\n",
                    "# timestamp: ",as.character(Sys.time()),
                    "\n",
                    "# AMS",
                    "\n",
                    "#---------------",
                    "\n",
                    "\n",
                    file=fileLabel,
                    row.names="",
                    col.names="",
                    sep=""))
  # add the data frame now
  write.table(x=dF,
              file=fileLabel,
              sep=",",
              row.names=FALSE,
              append=TRUE) # append as TRUE will prevent overwriting of the metadata, and append the data onto that metadata
  } # close the for loop
} # close the function
########################################################

FileBuilder()


####################################################
# Function: regStats
# fit linear model, get regression stats
# input: 2-column data frame
# output: slope,p-value and r^2
#---------------------------------------------------
regStats <- function(d=NULL) {
  if(is.null(d)) {
    xVar <- runif(10)
    yVar <- runif(10)
    d <- data.frame(xVar,yVar)
  }
  # create a placeholder variable
  . <- lm(data=d,d[,2]~d[,1])
  . <- summary(.) # this keeps a temp variable and daisy-chains info that can be passed down
  statsList <- list(Slope=.$coefficients[2,1],
                    pVal=.$coefficients[2,4],
                    r2=.$r.squared)
  return(statsList)
} # close function

#---------------------------------------------------
library(TeachingDemos)
char2seed("Freezing March")
#---------------------------------------------------
# Globabl variables
fileFolder <- "RandomFilesHW10/"
nFiles <- 100
fileOut <- "StatsSummaryHW10.csv"

# Create 100 random data sets
FileBuilder(fileN=nFiles)

fileNames <- list.files(path=fileFolder)

# Create data frame to hold file summary statistics
ID <- seq_along(fileNames)
fileName <- fileNames
slope <- rep(NA,nFiles)
pVal <- rep(NA,nFiles)
r2 <- rep(NA,nFiles)

statsOut <- data.frame(ID,fileName,slope,pVal,r2)

# batch process by looping through individual files
for(i in seq_along(fileNames)){
  data <- read.table(file=paste(fileFolder,fileNames[i],sep=""),
                     sep=",",
                     header=TRUE) # read in next data file
  dClean <- data[complete.cases(data),] # get clean cases
  . <- regStats(dClean) # pull regression stats from clean file
  statsOut[i,3:5] <- unlist(.) # unlist, copy into last 3 columns
}

# set up output file and incorporate time stamp and minimal metadata
write.table(cat("# Summary stats for ",
                "batch processing of regression models","\n",
                "# timestamp: ",as.character(Sys.time()),"\n",
                "# AMS","\n",
                "# -----------------","\n",
                "\n",
                file=fileOut,
                row.names="",
                col.names="",
                sep=""))

# now add the data frame
write.table(x=statsOut,
            file=fileOut,
            row.names=FALSE,
            col.names=TRUE,
            sep=",",
            append=TRUE)
                     
```

### "Breaking" the program

I was able to "break" the program by increasing the number of NA values to the minimum allowable row numbers. I did this by changing the "fileSize=" and fileNA" parameters when calling the FileBuilder function.

```{r,warning=FALSE}
# FileBuilder(fileSize=c(15,30),fileNA=15)
# regStats()

# for(i in seq_along(fileNames)){
#  data <- read.table(file=paste(fileFolder,fileNames[i],sep=""),
#                     sep=",",
#                     header=TRUE) # read in next data file
#  dClean <- data[complete.cases(data),] # get clean cases
#  . <- regStats(dClean) # pull regression stats from clean file
#  statsOut[i,3:5] <- unlist(.) # unlist, copy into last 3 columns
# }
```

### Adding columns to the StatsSummary.csv file

```{r,warning=FALSE}
ID <- seq_along(fileNames)
fileName <- fileNames
slope <- rep(NA,nFiles)
pVal <- rep(NA,nFiles)
r2 <- rep(NA,nFiles)
nRowOrig <- rep(NA,nFiles)
nRowClean <- rep(NA,nFiles)

statsOut <- data.frame(ID,fileName,slope,pVal,r2,nRowOrig,nRowClean)
for(i in seq_along(fileNames)){
  data <- read.table(file=paste(fileFolder,fileNames[i],sep=""),
                     sep=",",
                     header=TRUE)
  nRowOrig <- nrow(data)
  dClean <- data[complete.cases(data),]
  nRowClean <- nrow(dClean)
  . <- regStats(dClean) 
  statsOut[i,3:7] <- c(unlist(.),nRowOrig,nRowClean)
}


write.table(cat("# Summary stats for ",
                "batch processing of regression models","\n",
                "# timestamp: ",as.character(Sys.time()),"\n",
                "# AMS","\n",
                "# -----------------","\n",
                "\n",
                file=fileOut,
                row.names="",
                col.names="",
                sep=""))

write.table(x=statsOut,
            file=fileOut,
            row.names=FALSE,
            col.names=TRUE,
            sep=",",
            append=TRUE)
                     
```
